# Generated by Django 4.2.3 on 2023-07-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
